### ISSUE TITLE
第一步训练准确率是多少？

### ISSUE THREAD

**Issue by weihua93** [Ylexx/Hierarchical-Bilinear-Pooling_Resnet_pytorch#2]
按照博主的参数配置，在第一步80epoch训练之后只能达到69.3%的准确率，微调100epoch之后，最后准确率是80%。
问下，第一步准确率对吗？是第一步准确率低导致的第二步准确率低吗？

**Comment by Ylexx** [comment]
第一步训完准确率在79%左右，你这个情况确实是第一步准确率低导致的第二步准确率低

**Comment by weihua93** [comment]
> 第一步训完准确率在79%左右，你这个情况确实是第一步准确率低导致的第二步准确率低

我完全按照你的配置来的，你大概训练了多少个epoch达到79%的准确率？

**Comment by Ylexx** [comment]
80个epoch，你从pytorch官网下载resnet预训练参数了吗

**Comment by weihua93** [comment]
> 80个epoch，你从pytorch官网下载resnet预训练参数了吗

下了，不过我对代码数据初始读入的修改了一下，因为我没有txt文件，但这会有影响吗？

**Comment by Ylexx** [comment]
> > 80个epoch，你从pytorch官网下载resnet预训练参数了吗
> 
> 下了，不过我对代码数据初始读入的修改了一下，因为我没有txt文件，但这会有影响吗？

确认你读数据label对应没出问题，另外可以去我另一个项目bilinear_cnn下下载CUB200的txt文件

**Comment by weihua93** [comment]
> > > 80个epoch，你从pytorch官网下载resnet预训练参数了吗
> > 
> > 
> > 下了，不过我对代码数据初始读入的修改了一下，因为我没有txt文件，但这会有影响吗？
> 
> 确认你读数据label对应没出问题，另外可以去我另一个项目bilinear_cnn下下载CUB200的txt文件

那我去下TXT文件再试试，非常感谢～

**Comment by KindredSpirithub** [comment]
参照这个代码，我第一步训练也只能达到69.4%左右的精度
